spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500000MB
      max-request-size: 500000MB
  profiles:
    active: local
  jackson:
    serialization:
      indent_output: true
management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "refresh", "env", "metrics" ]

#Spring Cloud
spring.cloud.config.uri: http://localhost:8888
spring.cloud.config.username: configuser
spring.cloud.config.password: Secret123

spring.security.user.name: user
spring.security.user.password: pass

# Mongodb connection
spring.data.mongodb.uri: mongodb://localhost:27017/demo?waitQueueMultiple=10&maxPoolSize=150

# JWT Signing Key
jwt.signing.key: 123


#S3
# Minio access key (login)
s3.access.key: minioadmin
# Minio secret key (password)
s3.secret.key: minioadmin
# Minio Host
s3.service.endpoint: http://localhost:9000
s3.bucket.name: fus