spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500000MB
      max-request-size: 500000MB
  profiles:
    active: local

jwt:
  clientId: user
  jwtSecret: secret
  jwtExpirationMs: 86400000

# Mongodb connection
spring.data.mongodb.uri: mongodb://localhost:27017/demo

# Minio access key (login)
s3:
  access.key: minioadmin
  # Minio secret key (password)
  secret.key: minioadmin
  # Minio Host
  service.endpoint: http://localhost:9000
  bucket.name: fus

#Docker API
docker:
  host: tcp://127.0.0.1:2375

# Caddy API
caddy:
  host: localhost:2019

# Documentation
springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    enabled: true
  version: 0.0.3