spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500000MB
      max-request-size: 500000MB
  profiles:
    active: local

jwt:
  clientId: user
  jwtSecret: secret
  jwtExpirationMs: 86400000

# Mongodb connection
spring.data.mongodb.uri: mongodb://localhost:27017/demo

#S3
# Minio access key (login)
s3.access.key: minioadmin
# Minio secret key (password)
s3.secret.key: minioadmin
# Minio Host
s3.service.endpoint: http://localhost:9000
s3.bucket.name: fus

docker:
  host: tcp://127.0.0.1:2375