spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500000MB
      max-request-size: 500000MB

#Spring Cloud
spring.cloud.config.uri: http://localhost:8888
spring.cloud.config.username: configuser
spring.cloud.config.password: Secret123

spring.security.user.name: user
spring.security.user.password: pass

# Mongodb connection
spring.data.mongodb.uri: mongodb://localhost:27017/demo?waitQueueMultiple=10&maxPoolSize=150

# JWT Signing Key
jwt.signing.key: 123

# Minio Host
minio.url: http://localhost:9000
# Minio Bucket name for your application
minio.bucket: fus
# Minio access key (login)
minio.access-key: minioadmin
# Minio secret key (password)
minio.secret-key: minioadmin